IF EXISTS (SELECT * FROM MoviePortal.sys.objects WHERE type = 'P' AND name = 'usp_UpdateMovie')
BEGIN
DROP Procedure [dbo].[usp_UpdateMovie]
END

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE Procedure [dbo].[usp_UpdateMovie]

(
	 @MOVIE_ANID		INT
	,@CREW_ANID			INT
	,@ACTORS			NVARCHAR(4000)
	,@PRODUCER_ANID		INT
	,@MOVIE_NAME		NVARCHAR(400)
	,@UPDATED_BY		NVARCHAR(600)
	,@MOVIE_YOR			NVARCHAR(100)
	,@MOVIE_PLOT		NVARCHAR(MAX)
	,@MOVIE_POSTER		NVARCHAR(MAX)
)

AS

BEGIN
SET NOCOUNT ON

DECLARE  
		 @ErrMsg				NVARCHAR(510) --
		,@ErrorSeverity			INT --16 if business error

BEGIN

	
		IF(LEN(@MOVIE_NAME) >0)
		BEGIN
			UPDATE MOVIES  SET MOVIE_NAME = @MOVIE_NAME,MOVIE_YOR=@MOVIE_YOR,MOVIE_PLOT=@MOVIE_PLOT,MOVIE_POSTER=@MOVIE_POSTER,UPDATED_BY=@UPDATED_BY, UPDATED_DTTM=GETDATE() WHERE MOVIE_ANID = @MOVIE_ANID 
		END

		UPDATE CREW_UNION SET ACTOR_ANIDS = @ACTORS, PRODUCER_ANID=@PRODUCER_ANID, UPDATED_BY=@UPDATED_BY, UPDATED_DTTM=GETDATE() WHERE CREWUNION_ANID =@CREW_ANID AND MOVIE_ANID = @MOVIE_ANID

		SELECT @@ROWCOUNT
		
END
GOTO SUCCESS

SUCCESS:
RETURN 1
CRASH:
RAISERROR (@ErrMsg, @ErrorSeverity, 1) WITH NOWAIT
END
GO
GRANT EXEC ON [dbo].[usp_UpdateMovie] TO PUBLIC

GO
