//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviePortalDeltaX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTO
    {
        public int ACTOR_ANID { get; set; }
        public string ACTOR_NAME { get; set; }
        public string ACTOR_GENDER { get; set; }
        public Nullable<System.DateTime> ACTOR_DOB { get; set; }
        public string ACTOR_BIO { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DTTM { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DTTM { get; set; }
    }
}
