//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Data;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Data.Entity.Core.EntityClient;

[assembly: EdmSchemaAttribute()]
namespace MoviePortalDeltaX
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MoviePortalEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MoviePortalEntities object using the connection string found in the 'MoviePortalEntities' section of the application configuration file.
        /// </summary>
        public MoviePortalEntities() : base("name=MoviePortalEntities", "MoviePortalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MoviePortalEntities object.
        /// </summary>
        public MoviePortalEntities(string connectionString) : base(connectionString, "MoviePortalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MoviePortalEntities object.
        /// </summary>
        public MoviePortalEntities(EntityConnection connection) : base(connection, "MoviePortalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ACTOR> ACTORS
        {
            get
            {
                if ((_ACTORS == null))
                {
                    _ACTORS = base.CreateObjectSet<ACTOR>("ACTORS");
                }
                return _ACTORS;
            }
        }
        private ObjectSet<ACTOR> _ACTORS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MOVy> MOVIES
        {
            get
            {
                if ((_MOVIES == null))
                {
                    _MOVIES = base.CreateObjectSet<MOVy>("MOVIES");
                }
                return _MOVIES;
            }
        }
        private ObjectSet<MOVy> _MOVIES;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PRODUCER> PRODUCERS
        {
            get
            {
                if ((_PRODUCERS == null))
                {
                    _PRODUCERS = base.CreateObjectSet<PRODUCER>("PRODUCERS");
                }
                return _PRODUCERS;
            }
        }
        private ObjectSet<PRODUCER> _PRODUCERS;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ACTORS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToACTORS(ACTOR aCTOR)
        {
            base.AddObject("ACTORS", aCTOR);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MOVIES EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMOVIES(MOVy mOVy)
        {
            base.AddObject("MOVIES", mOVy);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PRODUCERS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPRODUCERS(PRODUCER pRODUCER)
        {
            base.AddObject("PRODUCERS", pRODUCER);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MoviePortalModel", Name="ACTOR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ACTOR : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ACTOR object.
        /// </summary>
        /// <param name="aCTOR_ANID">Initial value of the ACTOR_ANID property.</param>
        public static ACTOR CreateACTOR(global::System.Int32 aCTOR_ANID)
        {
            ACTOR aCTOR = new ACTOR();
            aCTOR.ACTOR_ANID = aCTOR_ANID;
            return aCTOR;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ACTOR_ANID
        {
            get
            {
                return _ACTOR_ANID;
            }
            set
            {
                if (_ACTOR_ANID != value)
                {
                    OnACTOR_ANIDChanging(value);
                    ReportPropertyChanging("ACTOR_ANID");
                    _ACTOR_ANID = StructuralObject.SetValidValue(value, "ACTOR_ANID");
                    ReportPropertyChanged("ACTOR_ANID");
                    OnACTOR_ANIDChanged();
                }
            }
        }
        private global::System.Int32 _ACTOR_ANID;
        partial void OnACTOR_ANIDChanging(global::System.Int32 value);
        partial void OnACTOR_ANIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACTOR_NAME
        {
            get
            {
                return _ACTOR_NAME;
            }
            set
            {
                OnACTOR_NAMEChanging(value);
                ReportPropertyChanging("ACTOR_NAME");
                _ACTOR_NAME = StructuralObject.SetValidValue(value, true, "ACTOR_NAME");
                ReportPropertyChanged("ACTOR_NAME");
                OnACTOR_NAMEChanged();
            }
        }
        private global::System.String _ACTOR_NAME;
        partial void OnACTOR_NAMEChanging(global::System.String value);
        partial void OnACTOR_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACTOR_GENDER
        {
            get
            {
                return _ACTOR_GENDER;
            }
            set
            {
                OnACTOR_GENDERChanging(value);
                ReportPropertyChanging("ACTOR_GENDER");
                _ACTOR_GENDER = StructuralObject.SetValidValue(value, true, "ACTOR_GENDER");
                ReportPropertyChanged("ACTOR_GENDER");
                OnACTOR_GENDERChanged();
            }
        }
        private global::System.String _ACTOR_GENDER;
        partial void OnACTOR_GENDERChanging(global::System.String value);
        partial void OnACTOR_GENDERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ACTOR_DOB
        {
            get
            {
                return _ACTOR_DOB;
            }
            set
            {
                OnACTOR_DOBChanging(value);
                ReportPropertyChanging("ACTOR_DOB");
                _ACTOR_DOB = StructuralObject.SetValidValue(value, "ACTOR_DOB");
                ReportPropertyChanged("ACTOR_DOB");
                OnACTOR_DOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _ACTOR_DOB;
        partial void OnACTOR_DOBChanging(Nullable<global::System.DateTime> value);
        partial void OnACTOR_DOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACTOR_BIO
        {
            get
            {
                return _ACTOR_BIO;
            }
            set
            {
                OnACTOR_BIOChanging(value);
                ReportPropertyChanging("ACTOR_BIO");
                _ACTOR_BIO = StructuralObject.SetValidValue(value, true, "ACTOR_BIO");
                ReportPropertyChanged("ACTOR_BIO");
                OnACTOR_BIOChanged();
            }
        }
        private global::System.String _ACTOR_BIO;
        partial void OnACTOR_BIOChanging(global::System.String value);
        partial void OnACTOR_BIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CREATED_BY
        {
            get
            {
                return _CREATED_BY;
            }
            set
            {
                OnCREATED_BYChanging(value);
                ReportPropertyChanging("CREATED_BY");
                _CREATED_BY = StructuralObject.SetValidValue(value, true, "CREATED_BY");
                ReportPropertyChanged("CREATED_BY");
                OnCREATED_BYChanged();
            }
        }
        private global::System.String _CREATED_BY;
        partial void OnCREATED_BYChanging(global::System.String value);
        partial void OnCREATED_BYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATED_DTTM
        {
            get
            {
                return _CREATED_DTTM;
            }
            set
            {
                OnCREATED_DTTMChanging(value);
                ReportPropertyChanging("CREATED_DTTM");
                _CREATED_DTTM = StructuralObject.SetValidValue(value, "CREATED_DTTM");
                ReportPropertyChanged("CREATED_DTTM");
                OnCREATED_DTTMChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATED_DTTM;
        partial void OnCREATED_DTTMChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATED_DTTMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UPDATED_BY
        {
            get
            {
                return _UPDATED_BY;
            }
            set
            {
                OnUPDATED_BYChanging(value);
                ReportPropertyChanging("UPDATED_BY");
                _UPDATED_BY = StructuralObject.SetValidValue(value, true, "UPDATED_BY");
                ReportPropertyChanged("UPDATED_BY");
                OnUPDATED_BYChanged();
            }
        }
        private global::System.String _UPDATED_BY;
        partial void OnUPDATED_BYChanging(global::System.String value);
        partial void OnUPDATED_BYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATED_DTTM
        {
            get
            {
                return _UPDATED_DTTM;
            }
            set
            {
                OnUPDATED_DTTMChanging(value);
                ReportPropertyChanging("UPDATED_DTTM");
                _UPDATED_DTTM = StructuralObject.SetValidValue(value, "UPDATED_DTTM");
                ReportPropertyChanged("UPDATED_DTTM");
                OnUPDATED_DTTMChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATED_DTTM;
        partial void OnUPDATED_DTTMChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATED_DTTMChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MoviePortalModel", Name="MOVy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MOVy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MOVy object.
        /// </summary>
        /// <param name="mOVIE_ANID">Initial value of the MOVIE_ANID property.</param>
        public static MOVy CreateMOVy(global::System.Int32 mOVIE_ANID)
        {
            MOVy mOVy = new MOVy();
            mOVy.MOVIE_ANID = mOVIE_ANID;
            return mOVy;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MOVIE_ANID
        {
            get
            {
                return _MOVIE_ANID;
            }
            set
            {
                if (_MOVIE_ANID != value)
                {
                    OnMOVIE_ANIDChanging(value);
                    ReportPropertyChanging("MOVIE_ANID");
                    _MOVIE_ANID = StructuralObject.SetValidValue(value, "MOVIE_ANID");
                    ReportPropertyChanged("MOVIE_ANID");
                    OnMOVIE_ANIDChanged();
                }
            }
        }
        private global::System.Int32 _MOVIE_ANID;
        partial void OnMOVIE_ANIDChanging(global::System.Int32 value);
        partial void OnMOVIE_ANIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MOVIE_NAME
        {
            get
            {
                return _MOVIE_NAME;
            }
            set
            {
                OnMOVIE_NAMEChanging(value);
                ReportPropertyChanging("MOVIE_NAME");
                _MOVIE_NAME = StructuralObject.SetValidValue(value, true, "MOVIE_NAME");
                ReportPropertyChanged("MOVIE_NAME");
                OnMOVIE_NAMEChanged();
            }
        }
        private global::System.String _MOVIE_NAME;
        partial void OnMOVIE_NAMEChanging(global::System.String value);
        partial void OnMOVIE_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MOVIE_YOR
        {
            get
            {
                return _MOVIE_YOR;
            }
            set
            {
                OnMOVIE_YORChanging(value);
                ReportPropertyChanging("MOVIE_YOR");
                _MOVIE_YOR = StructuralObject.SetValidValue(value, true, "MOVIE_YOR");
                ReportPropertyChanged("MOVIE_YOR");
                OnMOVIE_YORChanged();
            }
        }
        private global::System.String _MOVIE_YOR;
        partial void OnMOVIE_YORChanging(global::System.String value);
        partial void OnMOVIE_YORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MOVIE_PLOT
        {
            get
            {
                return _MOVIE_PLOT;
            }
            set
            {
                OnMOVIE_PLOTChanging(value);
                ReportPropertyChanging("MOVIE_PLOT");
                _MOVIE_PLOT = StructuralObject.SetValidValue(value, true, "MOVIE_PLOT");
                ReportPropertyChanged("MOVIE_PLOT");
                OnMOVIE_PLOTChanged();
            }
        }
        private global::System.String _MOVIE_PLOT;
        partial void OnMOVIE_PLOTChanging(global::System.String value);
        partial void OnMOVIE_PLOTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] MOVIE_POSTER
        {
            get
            {
                return StructuralObject.GetValidValue(_MOVIE_POSTER);
            }
            set
            {
                OnMOVIE_POSTERChanging(value);
                ReportPropertyChanging("MOVIE_POSTER");
                _MOVIE_POSTER = StructuralObject.SetValidValue(value, true, "MOVIE_POSTER");
                ReportPropertyChanged("MOVIE_POSTER");
                OnMOVIE_POSTERChanged();
            }
        }
        private global::System.Byte[] _MOVIE_POSTER;
        partial void OnMOVIE_POSTERChanging(global::System.Byte[] value);
        partial void OnMOVIE_POSTERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CREATED_BY
        {
            get
            {
                return _CREATED_BY;
            }
            set
            {
                OnCREATED_BYChanging(value);
                ReportPropertyChanging("CREATED_BY");
                _CREATED_BY = StructuralObject.SetValidValue(value, true, "CREATED_BY");
                ReportPropertyChanged("CREATED_BY");
                OnCREATED_BYChanged();
            }
        }
        private global::System.String _CREATED_BY;
        partial void OnCREATED_BYChanging(global::System.String value);
        partial void OnCREATED_BYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATED_DTTM
        {
            get
            {
                return _CREATED_DTTM;
            }
            set
            {
                OnCREATED_DTTMChanging(value);
                ReportPropertyChanging("CREATED_DTTM");
                _CREATED_DTTM = StructuralObject.SetValidValue(value, "CREATED_DTTM");
                ReportPropertyChanged("CREATED_DTTM");
                OnCREATED_DTTMChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATED_DTTM;
        partial void OnCREATED_DTTMChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATED_DTTMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UPDATED_BY
        {
            get
            {
                return _UPDATED_BY;
            }
            set
            {
                OnUPDATED_BYChanging(value);
                ReportPropertyChanging("UPDATED_BY");
                _UPDATED_BY = StructuralObject.SetValidValue(value, true, "UPDATED_BY");
                ReportPropertyChanged("UPDATED_BY");
                OnUPDATED_BYChanged();
            }
        }
        private global::System.String _UPDATED_BY;
        partial void OnUPDATED_BYChanging(global::System.String value);
        partial void OnUPDATED_BYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATED_DTTM
        {
            get
            {
                return _UPDATED_DTTM;
            }
            set
            {
                OnUPDATED_DTTMChanging(value);
                ReportPropertyChanging("UPDATED_DTTM");
                _UPDATED_DTTM = StructuralObject.SetValidValue(value, "UPDATED_DTTM");
                ReportPropertyChanged("UPDATED_DTTM");
                OnUPDATED_DTTMChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATED_DTTM;
        partial void OnUPDATED_DTTMChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATED_DTTMChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MoviePortalModel", Name="PRODUCER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PRODUCER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PRODUCER object.
        /// </summary>
        /// <param name="pRODUCER_ANID">Initial value of the PRODUCER_ANID property.</param>
        public static PRODUCER CreatePRODUCER(global::System.Int32 pRODUCER_ANID)
        {
            PRODUCER pRODUCER = new PRODUCER();
            pRODUCER.PRODUCER_ANID = pRODUCER_ANID;
            return pRODUCER;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PRODUCER_ANID
        {
            get
            {
                return _PRODUCER_ANID;
            }
            set
            {
                if (_PRODUCER_ANID != value)
                {
                    OnPRODUCER_ANIDChanging(value);
                    ReportPropertyChanging("PRODUCER_ANID");
                    _PRODUCER_ANID = StructuralObject.SetValidValue(value, "PRODUCER_ANID");
                    ReportPropertyChanged("PRODUCER_ANID");
                    OnPRODUCER_ANIDChanged();
                }
            }
        }
        private global::System.Int32 _PRODUCER_ANID;
        partial void OnPRODUCER_ANIDChanging(global::System.Int32 value);
        partial void OnPRODUCER_ANIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRODUCER_NAME
        {
            get
            {
                return _PRODUCER_NAME;
            }
            set
            {
                OnPRODUCER_NAMEChanging(value);
                ReportPropertyChanging("PRODUCER_NAME");
                _PRODUCER_NAME = StructuralObject.SetValidValue(value, true, "PRODUCER_NAME");
                ReportPropertyChanged("PRODUCER_NAME");
                OnPRODUCER_NAMEChanged();
            }
        }
        private global::System.String _PRODUCER_NAME;
        partial void OnPRODUCER_NAMEChanging(global::System.String value);
        partial void OnPRODUCER_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRODUCER_GENDER
        {
            get
            {
                return _PRODUCER_GENDER;
            }
            set
            {
                OnPRODUCER_GENDERChanging(value);
                ReportPropertyChanging("PRODUCER_GENDER");
                _PRODUCER_GENDER = StructuralObject.SetValidValue(value, true, "PRODUCER_GENDER");
                ReportPropertyChanged("PRODUCER_GENDER");
                OnPRODUCER_GENDERChanged();
            }
        }
        private global::System.String _PRODUCER_GENDER;
        partial void OnPRODUCER_GENDERChanging(global::System.String value);
        partial void OnPRODUCER_GENDERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PRODUCER_DOB
        {
            get
            {
                return _PRODUCER_DOB;
            }
            set
            {
                OnPRODUCER_DOBChanging(value);
                ReportPropertyChanging("PRODUCER_DOB");
                _PRODUCER_DOB = StructuralObject.SetValidValue(value, "PRODUCER_DOB");
                ReportPropertyChanged("PRODUCER_DOB");
                OnPRODUCER_DOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _PRODUCER_DOB;
        partial void OnPRODUCER_DOBChanging(Nullable<global::System.DateTime> value);
        partial void OnPRODUCER_DOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRODUCER_BIO
        {
            get
            {
                return _PRODUCER_BIO;
            }
            set
            {
                OnPRODUCER_BIOChanging(value);
                ReportPropertyChanging("PRODUCER_BIO");
                _PRODUCER_BIO = StructuralObject.SetValidValue(value, true, "PRODUCER_BIO");
                ReportPropertyChanged("PRODUCER_BIO");
                OnPRODUCER_BIOChanged();
            }
        }
        private global::System.String _PRODUCER_BIO;
        partial void OnPRODUCER_BIOChanging(global::System.String value);
        partial void OnPRODUCER_BIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CREATED_BY
        {
            get
            {
                return _CREATED_BY;
            }
            set
            {
                OnCREATED_BYChanging(value);
                ReportPropertyChanging("CREATED_BY");
                _CREATED_BY = StructuralObject.SetValidValue(value, true, "CREATED_BY");
                ReportPropertyChanged("CREATED_BY");
                OnCREATED_BYChanged();
            }
        }
        private global::System.String _CREATED_BY;
        partial void OnCREATED_BYChanging(global::System.String value);
        partial void OnCREATED_BYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATED_DTTM
        {
            get
            {
                return _CREATED_DTTM;
            }
            set
            {
                OnCREATED_DTTMChanging(value);
                ReportPropertyChanging("CREATED_DTTM");
                _CREATED_DTTM = StructuralObject.SetValidValue(value, "CREATED_DTTM");
                ReportPropertyChanged("CREATED_DTTM");
                OnCREATED_DTTMChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATED_DTTM;
        partial void OnCREATED_DTTMChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATED_DTTMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UPDATED_BY
        {
            get
            {
                return _UPDATED_BY;
            }
            set
            {
                OnUPDATED_BYChanging(value);
                ReportPropertyChanging("UPDATED_BY");
                _UPDATED_BY = StructuralObject.SetValidValue(value, true, "UPDATED_BY");
                ReportPropertyChanged("UPDATED_BY");
                OnUPDATED_BYChanged();
            }
        }
        private global::System.String _UPDATED_BY;
        partial void OnUPDATED_BYChanging(global::System.String value);
        partial void OnUPDATED_BYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATED_DTTM
        {
            get
            {
                return _UPDATED_DTTM;
            }
            set
            {
                OnUPDATED_DTTMChanging(value);
                ReportPropertyChanging("UPDATED_DTTM");
                _UPDATED_DTTM = StructuralObject.SetValidValue(value, "UPDATED_DTTM");
                ReportPropertyChanged("UPDATED_DTTM");
                OnUPDATED_DTTMChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATED_DTTM;
        partial void OnUPDATED_DTTMChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATED_DTTMChanged();

        #endregion

    }

    #endregion

}
